on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Run Linting
      run: platformio check --fail-on-defect=low --fail-on-defect=medium --fail-on-defect=high
